# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-10-13 05:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='token',
            old_name='meaning',
            new_name='sense',
        ),
    ]
