# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-28 02:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='type',
            field=models.IntegerField(),
        ),
    ]
