# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-05 18:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0003_dict'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dict',
            name='pos',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
